Event Editor
difcsi/e5vosdosite pull request #306
Opened 2023-10-31 20:00 UTC by barnagoz

## Progress

- [ ] #220 
- [ ] #219 
- [ ] #221
- [ ] #222 
- [ ] #218 

Fixes: #223

2023-11-02 18:13 UTC, barnagoz commented
A create event page gate-je a következő commitban meg lesz oldva.

2023-11-02 20:39 UTC, difcsi commented
Build and test workflow broken on this branch: will be fixed after other PR is merged. Will admin bypass when merging

2023-11-03 00:59 UTC, barnagoz commented
Should be ready for review. #222 will be done seperately

2023-11-03 02:06 UTC, difcsi commented on resources/frontend/pages/event/create.tsx
> -export default gated(CreateEventPage, isOperator);
Reverting this to isAdmin. We don't want fake event spam

2023-11-03 02:43 UTC, difcsi requested changes
Kicsit sok a duplikáció, meg néha a copypaste miatt lemaradt pár feature (event editor nem tölti be az értékeket)

2023-11-03 02:43 UTC, difcsi commented on resources/frontend/pages/event/[eventid]/manage/edit.tsx
Itt ez nem lesz így jó

2023-11-03 02:51 UTC, difcsi commented
closing PR as it has been merged with other PR: CRUD boilerplate present there could make this way simpler

2023-11-03 02:51 UTC, closed without merging